# ==========================================================================
# CRE PROJECT SETTINGS FILE - Tapl Workflows
# ==========================================================================

local-simulation:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://eth-sepolia.api.onfinality.io/public

worldchain:
  rpcs:
    - chain-name: ethereum-mainnet-worldchain-1
      url: https://soft-damp-dawn.worldchain-mainnet.quiknode.pro/7bfe836c5a78f4396a23adc241367c5111859c43/

staging:
  cre-cli:
    don-family: "zone-a"
  account:
    workflow-owner-address: "(optional) Multi-signature contract address"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: ${RPC_URL_SEPOLIA}
    - chain-name: ethereum-mainnet-worldchain-1
      url: https://soft-damp-dawn.worldchain-mainnet.quiknode.pro/7bfe836c5a78f4396a23adc241367c5111859c43/

production:
  cre-cli:
    don-family: "zone-a"
  account:
    workflow-owner-address: "${WORKFLOW_OWNER_ADDRESS}"
  rpcs:
    - chain-name: ethereum-mainnet
      url: ${RPC_URL_MAINNET}
    - chain-name: ethereum-testnet-sepolia-base
      url: ${RPC_URL_BASE}
